development:
  adapter: postgresql
  encoding: unicode
  database: lifeatlas_development
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: lifeatlas_test
  pool: 5
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
